package:
  name: varna
  version: 0.93.1

source:
  git_rev: 0.93
  git_url: https://github.com/Sargueil-CiTCoM/VARNA

requirements:
  build:
    - ant
    - openjdk

  run:
    - openjdk


about:
  home: https://github.com/yannponty/VARNA 
  license: GPL3
  license_family: GPL3
  summary: Visualization Application for RNA  
